services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    platform: linux/arm64
    build:
      context: ./rails
    command: bash -c "bundle exec rails s -b '0.0.0.0' -p 3002"
    volumes:
      - ./rails:/myapp:cached
    ports:
      - 3002:3002
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql_data: