import CurrentUserFetch from '@/components/CurrentUserFetch'
import MUIProvider from '@/components/MUIProvider'
import SuccessSnackbar from '@/components/Snackbar'
import '@/styles/destyle.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MUIProvider>
          <CurrentUserFetch />
          {children}
          <SuccessSnackbar />
        </MUIProvider>
      </body>
    </html>
  )
}
