import CurrentUserFetch from '@/components/CurrentUserFetch'
import '@/styles/destyle.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CurrentUserFetch />
      <body>{children}</body>
    </html>
  )
}
